### ISSUE TITLE
Error build with gcc 9.2

### ISSUE THREAD

**Issue by Bittyby** [alliedmodders/amxmodx#806]
```
[15073] c++ -pipe -fno-strict-aliasing -Wall -Werror -Wno-uninitialized -Wno-unused -Wno-switch -Wno-format -Wno-format-security -m32 -fvisibility=hidden -Wno-narrowing -Wno-unused-result -Wno-error=sign-compare -Wno-parentheses -O2 -g3 -ggdb3 -Wno-invalid-offsetof -std=c++11 -fvisibility-inlines-hidden -Wno-delete-non-virtual-dtor -fno-rtti -DNDEBUG -D_LINUX -DPOSIX -DLINUX -DAMX_NOPROPLIST -DPAWN_CELL_SIZE=32 -DAMXMODX_BUILD -DAMXX_USE_VERSIONLIB -DAMXX_GENERATED_BUILD -DAMX_ANSIONLY -I /root/amxmodx/amxmodx/build/includes -I /root/amxmodx/amxmodx/support/versionlib -I /root/amxmodx/amxmodx/public -I /root/amxmodx/amxmodx/public/sdk -I /root/amxmodx/amxmodx/public/amtl -I /root/amxmodx/amxmodx/public/amtl/amtl -I /root/amxmodx/amxmodx/public/memtools -I /root/amxmodx/amxmodx/third_party -I /root/amxmodx/amxmodx/third_party/hashing -I /root/amxmodx/amxmodx/third_party/zlib -I /root/amxmodx/amxmodx/third_party/utf8rewind -H -c /root/amxmodx/amxmodx/compiler/amxxpc/amxxpc.cpp -o amxxpc.o
/root/amxmodx/amxmodx/compiler/amxxpc/amxxpc.cpp: In function ‘void ReadFileIntoPl(abl*, FILE*)’:
/root/amxmodx/amxmodx/compiler/amxxpc/amxxpc.cpp:244:26: error: taking address of packed member of ‘tagAMX_HEADER’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  244 |  amx_Align32((uint32_t *)&hdr.stp);
      |                          ^~~~~~~~
/root/amxmodx/amxmodx/compiler/amxxpc/amxxpc.cpp:245:26: error: taking address of packed member of ‘tagAMX_HEADER’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  245 |  amx_Align32((uint32_t *)&hdr.size);
      |                          ^~~~~~~~~
cc1plus: all warnings being treated as errors
[15072] c++ -pipe -fno-strict-aliasing -Wall -Werror -Wno-uninitialized -Wno-unused -Wno-switch -Wno-format -Wno-format-security -m32 -fvisibility=hidden -Wno-narrowing -Wno-unused-result -Wno-error=sign-compare -Wno-parentheses -O2 -g3 -ggdb3 -Wno-invalid-offsetof -std=c++11 -fvisibility-inlines-hidden -Wno-delete-non-virtual-dtor -fno-rtti -DNDEBUG -D_LINUX -DPOSIX -DLINUX -DAMX_NOPROPLIST -DPAWN_CELL_SIZE=32 -DAMXMODX_BUILD -DAMXX_USE_VERSIONLIB -DAMXX_GENERATED_BUILD -DAMX_ANSIONLY -I /root/amxmodx/amxmodx/build/includes -I /root/amxmodx/amxmodx/support/versionlib -I /root/amxmodx/amxmodx/public -I /root/amxmodx/amxmodx/public/sdk -I /root/amxmodx/amxmodx/public/amtl -I /root/amxmodx/amxmodx/public/amtl/amtl -I /root/amxmodx/amxmodx/public/memtools -I /root/amxmodx/amxmodx/third_party -I /root/amxmodx/amxmodx/third_party/hashing -I /root/amxmodx/amxmodx/third_party/zlib -I /root/amxmodx/amxmodx/third_party/utf8rewind -H -c /root/amxmodx/amxmodx/compiler/amxxpc/amx.cpp -o amx.o
/root/amxmodx/amxmodx/compiler/amxxpc/amx.cpp: In function ‘int amx_Init(AMX*, void*)’:
/root/amxmodx/amxmodx/compiler/amxxpc/amx.cpp:866:28: error: taking address of packed member of ‘tagAMX_HEADER’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  866 |     amx_Align32((uint32_t*)&hdr->nametable);
      |                            ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[15062] cc -pipe -fno-strict-aliasing -Wall -Werror -Wno-uninitialized -Wno-unused -Wno-switch -Wno-format -Wno-format-security -m32 -fvisibility=hidden -Wno-narrowing -Wno-unused-result -Wno-error=sign-compare -Wno-parentheses -O2 -g3 -ggdb3 -std=c99 -DNDEBUG -D_LINUX -DPOSIX -DLINUX -DAMX_NOPROPLIST -DPAWN_CELL_SIZE=32 -DAMXMODX_BUILD -DAMXX_USE_VERSIONLIB -DAMXX_GENERATED_BUILD -DENABLE_BINRELOC -DNO_MAIN -DPAWNC_DLL -DHAVE_STDINT_H -D_GNU_SOURCE -I /root/amxmodx/amxmodx/build/includes -I /root/amxmodx/amxmodx/support/versionlib -I /root/amxmodx/amxmodx/public -I /root/amxmodx/amxmodx/public/sdk -I /root/amxmodx/amxmodx/public/amtl -I /root/amxmodx/amxmodx/public/amtl/amtl -I /root/amxmodx/amxmodx/public/memtools -I /root/amxmodx/amxmodx/third_party -I /root/amxmodx/amxmodx/third_party/hashing -I /root/amxmodx/amxmodx/third_party/zlib -I /root/amxmodx/amxmodx/third_party/utf8rewind -I /root/amxmodx/amxmodx/compiler/libpc300 -I /root/amxmodx/amxmodx/build/compiler/libpc300 -H -c /root/amxmodx/amxmodx/compiler/libpc300/sc1.c -o sc1.o
In file included from /usr/include/string.h:494,
                 from /root/amxmodx/amxmodx/compiler/libpc300/sc1.c:30:
In function ‘strncpy’,
    inlined from ‘setconfig’ at /root/amxmodx/amxmodx/compiler/libpc300/sc1.c:1348:7,
    inlined from ‘pc_compile’ at /root/amxmodx/amxmodx/compiler/libpc300/sc1.c:536:3:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Build failed.

```

**Comment by Bittyby** [comment]
@Arkshine
